// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// import Navbar from "@/components/main";
// import FooterComponent from "@/components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <Navbar/>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >

//         {children}
        
//       </body>
//       <FooterComponent />
//     </html>
//   );
// }


import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/main";
import FooterComponent from "@/components/footer";
import PageLoader from "@/components/pageloader"; // Create this component

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "LearnPro | Your Learning Journey",
  description: "Transformative online learning experiences",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased bg-gray-50 min-h-screen flex flex-col">
        <PageLoader />
        
        <div className="flex flex-col min-h-screen">
          <Navbar />
          
          <main className="flex-grow">
            {children}
          </main>
          
          <FooterComponent />
        </div>
      </body>
    </html>
  );
}